# Browser configuration
browser=chrome

# Application URL
#baseURL=https://admin-demo.nopcommerce.com/

# Login credentials
#username=[email protected]
#password=admin

# Driver paths (optional if using WebDriverManager)
#chromepath=./Drivers/chromedriver.exe
#firefoxpath=./Drivers/geckodriver.exe
#iepath=./Drivers/IEDriverServer.exe